### ISSUE TITLE
Update GCP Image to Meilisearch v0.30.5

### ISSUE THREAD

**Issue by sanieldalib** [meilisearch/meilisearch-gcp#205]
**Description**
Currently the latest version of the GCP Image is `meilisearch-image/meilisearch-v0.30.4-debian-10.vmdk`. It would be great if you could update this for v0.30.5 of Meilisearch: https://github.com/meilisearch/meilisearch/releases/tag/v0.30.5

**Comment by alallema** [comment]
Hi @sanieldalib,
Yes I will try to release v0.30.5 this week also v1 of Meilisearch is coming soon 😍

**Comment by alallema** [comment]
The v0.30.5 is available as `meilisearch-image/meilisearch-v0.30.5-debian-10.vmdk` 🎉
