### ISSUE TITLE
How to check logs

### ISSUE THREAD

**Issue by allantatter** [meilisearch/meilisearch-gcp#26]
I followed Meilisearch Google Cloud Platform guide to setup Meilisearch (https://docs.meilisearch.com/create/how_to/gcp.html). For debugging this instance behaviour, I'd like to check Meilisearch's logs to see what's happening. I'd expected logs to be outputted to stdout/stderr but almost nothing ends up there (https://d.pr/i/9jNTcZ).

So where is the right place to look for internal logs?

**Comment by alallema** [comment]
Hi @allantatter,
There are no logs available in production mode. However, you can have some information about the status of Meilisearch with:
```
systemctl status meilisearch
```
And have all the log are available in the file `/var/log/syslog` not sure is helping a lot.
If you want to debug it is better to stay in development mode.

**Comment by alallema** [comment]
Closing due to lack of answer, feel free to re-open if needed of course 🙂
