### ISSUE TITLE
Meilisearch GCP image not available

### ISSUE THREAD

**Issue by mattbodman** [meilisearch/meilisearch-gcp#38]
When trying to access the virtual disk file gs://meilisearch-image/meilisearch-v0.24.0-debian-10.vmdk, the error was thrown "Object not available. Either it does not exist or you do not have access..."

![Screen Shot 2021-12-31 at 11 12 29 am](https://user-images.githubusercontent.com/1994501/147797418-5ca0a242-40a5-4b0f-8d1e-37632a80f975.png)

**Comment by alallema** [comment]
Hi @mattbodman,
GCP seems to have changed the format address it's now: `meilisearch-image/meilisearch-v0.24.0-debian-10.vmdk` without the `gs://`.
Sorry for the disagreement.
