### ISSUE TITLE
Unable to use image for deployment 

### ISSUE THREAD

**Issue by gabrieldlm** [meilisearch/meilisearch-gcp#39]
Following the [deployment docs](https://docs.meilisearch.com/learn/cookbooks/gcp.html) I'm unable to use the meilisearch image:

![Screenshot from 2022-01-12 16-32-50](https://user-images.githubusercontent.com/13759770/149209663-3d875ab5-d0a5-4673-8a87-d3cacc3f7ff9.png)

**Comment by curquiza** [comment]
Hello @gabrieldlm 

The maintainer of this repo @alallema is sick at the moment. She maybe did not have the time to finish the process to make the MeiliSearch v0.25.0 image available for GCP
Sorry for this, you should have more information about this error next week.
In the meantime
- you can still [install meilisearch v0.25.0 on your server](https://docs.meilisearch.com/learn/getting_started/installation.html#installation), even if it's more convenient as the image we provide, I agree.
- use the meilisearch v0.24.0 image on GCP

Sorry again!

**Comment by gabrieldlm** [comment]
Thanks for the response. Wishig full recover for Alallema

**Comment by alallema** [comment]
Hi @gabrieldlm,
Thanks.
For your trouble, yes the adresse has changed recently I don't know why. We have updated the documentation accordingly in the last release.
I'm closing this issue
