### ISSUE TITLE
Create unpublish-image.py

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch-gcp#7]
A script should automatically remove older images from the bucket.
This should use relatively the same process as https://github.com/meilisearch/meilisearch-aws/pull/19
Document its usage on the CONTRIBUTING.md file (Release process section)

**Comment by Rutam21** [comment]
@curquiza I would love to give it a try. Feel free to assign this to me. Let me know where to hop in case I need some help. THanks.

**Comment by Azanul** [comment]
Looks inactive. Can I take this up?

**Comment by alallema** [comment]
Closure of this issue due to the deprecation of this repository
